# Generated by Django 5.2.8 on 2025-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('category_image', models.ImageField(upload_to='category/images', verbose_name='Category Image')),
                ('category_description', models.TextField(verbose_name='Category Description')),
            ],
        ),
    ]
