# Generated by Django 5.2.8 on 2025-11-25 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('product_image', models.ImageField(upload_to='products/image', verbose_name='Product Image')),
                ('product_price', models.PositiveIntegerField(verbose_name='Product Price')),
                ('stock', models.PositiveIntegerField(verbose_name='Product Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Product Availability')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shop.categorymodel', verbose_name='Category')),
            ],
        ),
    ]
