# Generated by Django 5.2.8 on 2025-12-03 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Shop', '0002_productmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User Details'),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='Order id')),
                ('amount', models.IntegerField(verbose_name='Order Amount')),
                ('address', models.TextField(verbose_name='Customer Address')),
                ('phone', models.IntegerField(verbose_name='Customer Phone Number')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Ordering Date')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Is ordered')),
                ('delivery_status', models.CharField(default='pending', max_length=50, verbose_name='Delivery Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User Details')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Order Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.productmodel', verbose_name='Product Details')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.ordermodel', verbose_name='Order Details')),
            ],
        ),
    ]
