# Generated by Django 5.2.8 on 2025-12-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cartmodel_user_ordermodel_orderitemsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Cart.ordermodel', verbose_name='Order Details'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Deliver', 'Cash on Deliver'), ('Pay Online', 'Pay Online')], max_length=50, verbose_name='Payment Method'),
        ),
    ]
